version: "3.9"
services:
  grpc:
    container_name: grpcservedev
    build:      
      dockerfile: Dockerfile  
      context: . 
      target: grpcserver
    environment:
      - GRPCSERVICE_PORT=9000
      - GRPCSERVICE_HOST=grpc      
      - MYSQL_HOST=mysql
      - MYSQL_PORT=:3306    
      - USERS_REPOSITORY=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=BulkD3v_mysql
      - MYSQL_DEFAULTDB=users
    expose:
      - "9000"  
    networks:
      - internal
    depends_on:
            mysql:
                condition: service_healthy
  rest:
    container_name: restservdev
    build:
      dockerfile: Dockerfile
      context: . 
      target: restserver
    ports:
      - "8080:8080"
    environment:
      - GRPCSERVICE_HOST=grpc
      - GRPCSERVICE_PORT=9000
    networks:
      - internal
    depends_on:
      - grpc
  mysql:
    container_name: mysqlserver
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=BulkD3v_mysql
      - MYSQL_DATABASE=users
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./seeds/schema.sql:/docker-entrypoint-initdb.d/init.sql
    tty:
      true
    networks:
      - internal

networks:
  internal: {}
    
